version: '3'

services:
  site:
    image: tehusername/docker-swarm-demo-app:1.0
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:80"
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
