version: '3'

services:
  site:
    image: tehusername/docker-swarm-demo-app:2.0
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1s
      timeout: 2s
      retries: 3
    deploy:
      replicas: 2
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
